In [2]:
import numpy as np

In [3]:
n_max = 33
n_steps = 4
tss = np.logspace(start=1,
                                stop=np.log10(n_max),
                                num=n_steps).\
                            astype(np.int)
print(tss)

[10 14 22 33]


In [18]:
tss.shape

(4,)

In [23]:
np.argwhere(tss==46).ravel()==1

array([ True], dtype=bool)

In [17]:
np.argwhere(tss==46).ravel()

array([1])

In [9]:
list(np.arange(3))

[0, 1, 2]

In [10]:
import itertools
list(range(3))

[0, 1, 2]