In [2]:
import numpy as np

In [3]:
n_max = 33
n_steps = 4
tss = np.logspace(start=1,
                                stop=np.log10(n_max),
                                num=n_steps).\
                            astype(np.int)
print(tss)

[10 14 22 33]


In [18]:
tss.shape

(4,)

In [23]:
np.argwhere(tss==46).ravel()==1

array([ True], dtype=bool)

In [17]:
np.argwhere(tss==46).ravel()

array([1])

In [9]:
list(np.arange(3))

[0, 1, 2]

In [10]:
import itertools
list(range(3))

[0, 1, 2]

In [6]:
GenSamplesOneBit.__name__

'GenSamplesOneBit'

In [8]:
type('ABC', (), {})

__main__.ABC

In [13]:
from luigi_utils.sampling_framework import GenSample, GenSamples, FitModel, \
    EvaluateStatisticalDistance, ComputeConvergenceCurve
from luigi_utils.privacy_estimator_mixins import DensityEstFitterMixin, \
    ExpectationFitterMixin, KNNFitterMixin


def build_convergence_curve_pipeline(GenSampleType: GenSample,
                                     generate_in_batch=False,
                                     fitter = 'knn',
                                     ) -> ComputeConvergenceCurve:
    gs_name = GenSampleType.__name__
    GSs = type(gs_name+'GenSamples',
               (GenSamples(GenSampleType, generate_in_batch=generate_in_batch))
               , {}
               )

    if fitter=='knn':
        F = KNNFitterMixin
    elif fitter=='density':
        F = DensityEstFitterMixin
    elif fitter=='expectation':
        F = ExpectationFitterMixin

    FM = type(gs_name+'FitModel'+fitter,
              (F(), FitModel(GSs)), {}
              )

    ESD = type(gs_name+'EvaluateStatisticalDistance'+fitter,
               (EvaluateStatisticalDistance(samplegen=GSs, model=FM)), {}
               )

    CCC = type(gs_name+'ComputeConvergenceCurve'+fitter,
               (ComputeConvergenceCurve(ESD)), {}
               )

    return CCC



TypeError: type.__new__() argument 2 must be tuple, not Register

In [17]:
class GenSamplesOneBit(object):
    pass
GenSampleType = GenSamplesOneBit
gs_name = GenSampleType.__name__
GSs = type(gs_name+'GenSamples', (GenSampleType), {})

TypeError: type.__new__() argument 2 must be tuple, not type